project: 
  type: website
  
website: 
  title: "This is Stat 515"
  site-url: https://aboldbaa.github.io/website/
  navbar: 
    left: 
      - href: index.qmd
        text: Home
      - href: hello.qmd
        text: Hello
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo     
    
